[2023-12-20T23:06:04.030+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: bash_dag.print_hello scheduled__2020-10-06T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
