[2023-12-20T23:00:01.682+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: bash_dag.sleep scheduled__2020-10-11T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
