[2023-12-20T23:03:58.630+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_dag.print_hello scheduled__2020-10-02T00:00:00+00:00 [queued]>
[2023-12-20T23:03:59.992+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_dag.print_hello scheduled__2020-10-02T00:00:00+00:00 [queued]>
[2023-12-20T23:04:00.098+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2023-12-20T23:04:21.968+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): print_hello> on 2020-10-02 00:00:00+00:00
[2023-12-20T23:04:26.943+0000] {standard_task_runner.py:60} INFO - Started process 556 to run task
[2023-12-20T23:04:29.267+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'bash_dag', 'print_hello', 'scheduled__2020-10-02T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/util_dag_bash/bash_dag.py', '--cfg-path', '/tmp/tmp2fat3fmb']
[2023-12-20T23:04:33.175+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask print_hello
[2023-12-20T23:05:12.656+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task print_hello ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 556)
[2023-12-20T23:05:55.492+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-20T23:06:08.081+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
